import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { format } from "date-fns";
import type { WeeklyRetrospective } from "@/lib/types";

function StatTile({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border bg-muted/30 px-3 py-2">
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="text-lg font-semibold font-mono">{value}</div>
    </div>
  );
}

export function RetrospectiveList({ retrospectives }: { retrospectives: WeeklyRetrospective[] }) {
  if (retrospectives.length === 0) {
    return (
      <p className="text-sm text-muted-foreground py-8 text-center">
        No retrospectives yet — the first one is generated by the Friday weekly-grade cron job once
        there are picks to review.
      </p>
    );
  }

  return (
    <div className="space-y-4">
      {retrospectives.map((retro) => {
        const stats = retro.stats;
        return (
          <Card key={retro.id}>
            <CardHeader>
              <CardTitle>
                Week of {format(new Date(retro.week_start), "MMM d")} –{" "}
                {format(new Date(retro.week_end), "MMM d, yyyy")}
              </CardTitle>
              <CardDescription>{retro.summary}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <StatTile label="Picks" value={String(stats.pickCount ?? 0)} />
                <StatTile label="Win Rate" value={`${(stats.winRate ?? 0).toFixed(0)}%`} />
                <StatTile label="Avg Return" value={`${(stats.avgReturnPct ?? 0).toFixed(2)}%`} />
                <StatTile
                  label="Best Pick"
                  value={stats.bestPick ? `${stats.bestPick.ticker} +${stats.bestPick.returnPct.toFixed(1)}%` : "—"}
                />
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}
